# Use "gomake install" to build and install this package.
include $(GOROOT)/src/Make.inc

TARG=github.com/hanwen/go-fuse/examplelib

DEPS=../fuse

GOFILES=stackfs.go \
	zipfs.go \
	multizip.go \
	misc.go

include $(GOROOT)/src/Make.pkg

