# Use "gomake install" to build and install this package.
include $(GOROOT)/src/Make.inc

#TARG=github.com/krasin/go-fuse-zip/fuse
TARG=fuse

GOFILES=misc.go\
	fuse.go\
	mount.go\
	types.go\
	dummyfuse.go\
	pathfilesystem.go \
	passthrough.go\

include $(GOROOT)/src/Make.pkg

